FROM node:onbuild

ENV CERT_COUNTRY US
ENV CERT_STATE Denial
ENV CERT_LOCATION Unknown
ENV CERT_ORGANISATION Dis
ENV CERT_FQDN smtp.foo.com
ENV SMTP_USERNAME foo@bar.com
ENV SMTP_PASSWORD foopass

EXPOSE 435

ENTRYPOINT ["./entrypoint.sh"]